edition = "2018"

max_width = 80
array_width = 50

indent_style = "Block"
imports_indent = "Block"
use_small_heuristics = "Max"

reorder_modules = false
reorder_imports = false
merge_derives = true

error_on_line_overflow = true
error_on_unformatted = true
